"use client";

import { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import {
  X,
  MessageSquare,
  Send,
  Phone,
  AlertTriangle,
  Clock,
  Wrench,
  Zap,
  Activity,
  CheckCircle2,
  ExternalLink,
  ChevronDown,
} from "lucide-react";

/* ── Message Templates ──────────────────────────────────────────────────── */
export type AlertTemplate =
  | "overdue"
  | "damage_risk"
  | "due_soon"
  | "maintenance"
  | "high_idle"
  | "custom";

interface Template {
  id: AlertTemplate;
  label: string;
  icon: React.ElementType;
  color: string;
  severity: "critical" | "warning" | "info";
  buildMessage: (ctx: AlertContext) => string;
}

interface AlertContext {
  equipmentId: string;
  equipmentType: string;
  siteId?: string | null;
  operatorId?: string | null;
  daysOverdue?: number | null;
  daysUntilDue?: number | null;
  expectedReturnDate?: string | null;
  idleRatio?: number;
}

const TEMPLATES: Template[] = [
  {
    id: "overdue",
    label: "Overdue Return",
    icon: AlertTriangle,
    color: "#ef4444",
    severity: "critical",
    buildMessage: (ctx) =>
      `🚨 *URGENT — CAT® VisionLink® Rental Alert*\n\nDear Operator ${ctx.operatorId ?? ""},\n\nYour rented equipment *${ctx.equipmentType}* (Asset ID: *${ctx.equipmentId}*) assigned to site *${ctx.siteId ?? "N/A"}* is *${ctx.daysOverdue ?? "?"} day(s) OVERDUE* past the expected return date${ctx.expectedReturnDate ? ` of ${new Date(ctx.expectedReturnDate).toLocaleDateString()}` : ""}.\n\n⚠️ Continued use beyond the contracted period will incur *penalty charges*.\n\nPlease return the equipment immediately or contact us to extend your rental contract.\n\n📞 Cat® Equipment Services\n🌐 visionlink.cat.com`,
  },
  {
    id: "damage_risk",
    label: "Damage / Misuse Risk",
    icon: Zap,
    color: "#f87171",
    severity: "critical",
    buildMessage: (ctx) =>
      `⚠️ *CAT® VisionLink® — Equipment Damage Risk Alert*\n\nDear Operator ${ctx.operatorId ?? ""},\n\nOur telematics system has detected *abnormal usage patterns* on your rented equipment:\n\n🔴 Equipment: *${ctx.equipmentType}* (ID: *${ctx.equipmentId}*)\n📍 Site: *${ctx.siteId ?? "N/A"}*${ctx.idleRatio !== undefined ? `\n⏱️ Idle Ratio Detected: *${ctx.idleRatio.toFixed(0)}%* (threshold: 50%)` : ""}\n\n*Potential misuse or damage risk has been flagged.* Operating outside normal parameters may void your rental warranty.\n\nPlease conduct an immediate visual inspection and contact our service team.\n\n📞 Cat® Equipment Services`,
  },
  {
    id: "due_soon",
    label: "Return Due Soon",
    icon: Clock,
    color: "#f59e0b",
    severity: "warning",
    buildMessage: (ctx) =>
      `📅 *CAT® VisionLink® — Return Reminder*\n\nDear Operator ${ctx.operatorId ?? ""},\n\nThis is a friendly reminder that your rented equipment is approaching its return date:\n\n🚜 Equipment: *${ctx.equipmentType}* (ID: *${ctx.equipmentId}*)\n📍 Site: *${ctx.siteId ?? "N/A"}*\n📆 Return Due In: *${ctx.daysUntilDue ?? "?"} day(s)*${ctx.expectedReturnDate ? `\n🗓️ Return Date: *${new Date(ctx.expectedReturnDate).toLocaleDateString()}*` : ""}\n\nPlease prepare the equipment for return or contact us to arrange an extension.\n\nThank you for choosing Cat® Equipment.\n\n📞 Cat® Equipment Services`,
  },
  {
    id: "maintenance",
    label: "Maintenance Required",
    icon: Wrench,
    color: "#fbbf24",
    severity: "warning",
    buildMessage: (ctx) =>
      `🔧 *CAT® VisionLink® — Maintenance Alert*\n\nDear Operator ${ctx.operatorId ?? ""},\n\nOur telematics engine has flagged that the following equipment requires immediate maintenance inspection:\n\n🚜 Equipment: *${ctx.equipmentType}* (ID: *${ctx.equipmentId}*)\n📍 Site: *${ctx.siteId ?? "N/A"}*\n\n*Do not operate this unit* until it has been inspected by a certified Cat® technician. Continued operation may cause irreversible machine damage.\n\nPlease park the equipment safely and await our service team.\n\n📞 Cat® Service Dispatch`,
  },
  {
    id: "high_idle",
    label: "High Idle / Fuel Waste",
    icon: Activity,
    color: "#38bdf8",
    severity: "info",
    buildMessage: (ctx) =>
      `💡 *CAT® VisionLink® — Efficiency Advisory*\n\nDear Operator ${ctx.operatorId ?? ""},\n\nWe have noticed elevated idle hours on your equipment:\n\n🚜 Equipment: *${ctx.equipmentType}* (ID: *${ctx.equipmentId}*)\n📍 Site: *${ctx.siteId ?? "N/A"}*${ctx.idleRatio !== undefined ? `\n⏱️ Idle Ratio: *${ctx.idleRatio.toFixed(0)}%*` : ""}\n\nExcessive idling wastes fuel and increases engine wear. Please shut off the engine when not in active use.\n\nThis advisory is automatically generated by Cat® VisionLink® telematics.\n\n📞 Cat® Fleet Services`,
  },
  {
    id: "custom",
    label: "Custom Message",
    icon: MessageSquare,
    color: "#a855f7",
    severity: "info",
    buildMessage: () => "",
  },
];

const SEVERITY_BADGE: Record<string, string> = {
  critical: "cat-badge cat-badge-overdue",
  warning:  "cat-badge cat-badge-maintenance",
  info:     "cat-badge cat-badge-low",
};

interface SendAlertModalProps {
  open: boolean;
  onClose: () => void;
  context: AlertContext;
  defaultTemplate?: AlertTemplate;
}

export function SendAlertModal({
  open,
  onClose,
  context,
  defaultTemplate = "overdue",
}: SendAlertModalProps) {
  const [selectedTemplate, setSelectedTemplate] = useState<AlertTemplate>(defaultTemplate);
  const [phone, setPhone] = useState("");
  const [message, setMessage] = useState("");
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);

  const activeTemplate = TEMPLATES.find((t) => t.id === selectedTemplate)!;

  // Rebuild message when template or context changes
  useEffect(() => {
    if (selectedTemplate !== "custom") {
      setMessage(activeTemplate.buildMessage(context));
    }
  }, [selectedTemplate, context]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (open) {
      setSent(false);
      setSending(false);
      setPhone("");
      setSelectedTemplate(defaultTemplate);
    }
  }, [open, defaultTemplate]);

  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  if (!open || !mounted) return null;

  // WhatsApp wa.me URL (works without any API — opens WhatsApp directly)
  const encodedMsg = encodeURIComponent(message);
  const cleanPhone = phone.replace(/\D/g, "");
  const whatsappUrl = `https://wa.me/${cleanPhone}?text=${encodedMsg}`;

  async function handleSendBackend() {
    if (!cleanPhone || !message) return;
    setSending(true);
    try {
      const res = await fetch("http://localhost:8000/api/notifications/whatsapp", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          to: `+${cleanPhone}`,
          message,
          equipment_id: context.equipmentId,
          template: selectedTemplate,
        }),
      });
      if (!res.ok) throw new Error("API unavailable");
      setSent(true);
    } catch {
      // Fallback: open wa.me link
      window.open(whatsappUrl, "_blank");
      setSent(true);
    } finally {
      setSending(false);
    }
  }

  function handleOpenWhatsApp() {
    window.open(whatsappUrl, "_blank");
    setSent(true);
  }

  const charCount = message.length;
  const canSend = cleanPhone.length >= 10 && message.trim().length > 0;

  return createPortal(
    <div
      className="fixed inset-0 z-[1000] flex items-center justify-center p-4"
      style={{ background: "rgba(8,10,13,0.8)", backdropFilter: "blur(8px)" }}
      onClick={onClose}
    >
      <div
        className="w-full max-w-xl bg-[#131820] border border-[#21293a] rounded-2xl shadow-2xl cat-scale-in overflow-hidden"
        onClick={(e) => e.stopPropagation()}
        style={{ boxShadow: "0 32px 80px rgba(0,0,0,0.7), 0 0 0 1px rgba(255,255,255,0.04)" }}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-[#21293a] bg-[#0d1117]">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-[#25d366]/15 border border-[#25d366]/30 flex items-center justify-center">
              {/* WhatsApp icon SVG */}
              <svg viewBox="0 0 24 24" className="w-5 h-5 fill-[#25d366]">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.890-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/>
              </svg>
            </div>
            <div>
              <h2 className="text-sm font-black text-white uppercase tracking-wide">Send WhatsApp Alert</h2>
              <p className="text-[10px] text-[#5a6a7e] font-mono">
                Asset: <span className="text-[#ffcd11]">{context.equipmentId}</span> · {context.equipmentType}
              </p>
            </div>
          </div>
          <button onClick={onClose} className="cat-btn-icon">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="p-5 space-y-4 max-h-[70vh] overflow-y-auto">
          {sent ? (
            /* Success State */
            <div className="text-center py-8 space-y-3">
              <div className="w-16 h-16 rounded-full bg-[#25d366]/15 border border-[#25d366]/30 flex items-center justify-center mx-auto">
                <CheckCircle2 className="w-8 h-8 text-[#25d366]" />
              </div>
              <h3 className="text-base font-black text-white">Alert Dispatched!</h3>
              <p className="text-sm text-[#8898aa]">
                WhatsApp alert for <span className="text-white font-bold">{context.equipmentId}</span> has been sent.
              </p>
              <button onClick={onClose} className="cat-btn-primary mt-2">
                Done
              </button>
            </div>
          ) : (
            <>
              {/* Template Selector */}
              <div className="space-y-2">
                <label className="text-[10px] font-bold text-[#5a6a7e] uppercase tracking-wider">Alert Type</label>
                <button
                  onClick={() => setShowTemplates((s) => !s)}
                  className="w-full flex items-center gap-3 px-3.5 py-3 bg-[#0d1117] border border-[#21293a] rounded-xl hover:border-[#2d3848] transition-all"
                >
                  <div
                    className="w-7 h-7 rounded-lg flex items-center justify-center shrink-0"
                    style={{ background: `${activeTemplate.color}15`, border: `1px solid ${activeTemplate.color}30` }}
                  >
                    <activeTemplate.icon className="w-3.5 h-3.5" style={{ color: activeTemplate.color }} />
                  </div>
                  <span className="flex-1 text-left text-sm font-semibold text-white">{activeTemplate.label}</span>
                  <span className={SEVERITY_BADGE[activeTemplate.severity]}>{activeTemplate.severity}</span>
                  <ChevronDown className={`w-4 h-4 text-[#5a6a7e] transition-transform ${showTemplates ? "rotate-180" : ""}`} />
                </button>

                {showTemplates && (
                  <div className="border border-[#21293a] rounded-xl overflow-hidden bg-[#0d1117] cat-scale-in">
                    {TEMPLATES.map((t) => (
                      <button
                        key={t.id}
                        onClick={() => { setSelectedTemplate(t.id); setShowTemplates(false); }}
                        className={`w-full flex items-center gap-3 px-3.5 py-2.5 hover:bg-[#161b23] transition-colors text-left ${selectedTemplate === t.id ? "bg-[#161b23]" : ""}`}
                      >
                        <div
                          className="w-6 h-6 rounded-lg flex items-center justify-center shrink-0"
                          style={{ background: `${t.color}15`, border: `1px solid ${t.color}25` }}
                        >
                          <t.icon className="w-3 h-3" style={{ color: t.color }} />
                        </div>
                        <span className="text-sm text-[#e2e8f0]">{t.label}</span>
                        {selectedTemplate === t.id && (
                          <CheckCircle2 className="w-3.5 h-3.5 text-[#ffcd11] ml-auto" />
                        )}
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* Phone Number */}
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-[#5a6a7e] uppercase tracking-wider flex items-center gap-1.5">
                  <Phone className="w-3 h-3" /> Customer WhatsApp Number
                </label>
                <div className="flex items-center gap-2 bg-[#0d1117] border border-[#21293a] rounded-xl px-3.5 py-2.5 focus-within:border-[#25d366]/50 focus-within:shadow-[0_0_0_2px_rgba(37,211,102,0.08)] transition-all">
                  <span className="text-sm text-[#5a6a7e] font-mono shrink-0">+</span>
                  <input
                    type="tel"
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                    placeholder="91 98765 43210 (with country code)"
                    className="flex-1 bg-transparent text-sm text-white placeholder-[#5a6a7e] outline-none font-mono"
                  />
                </div>
                <p className="text-[10px] text-[#5a6a7e]">Include country code, e.g. 919876543210 for India</p>
              </div>

              {/* Message Editor */}
              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <label className="text-[10px] font-bold text-[#5a6a7e] uppercase tracking-wider">
                    Message Preview
                  </label>
                  <span className="text-[10px] font-mono text-[#5a6a7e]">{charCount} chars</span>
                </div>
                <textarea
                  value={message}
                  onChange={(e) => {
                    setMessage(e.target.value);
                    setSelectedTemplate("custom");
                  }}
                  rows={8}
                  className="w-full bg-[#0d1117] border border-[#21293a] rounded-xl px-4 py-3 text-xs text-[#e2e8f0] font-mono leading-relaxed outline-none resize-none focus:border-[#ffcd11]/40 focus:shadow-[0_0_0_2px_rgba(255,205,17,0.06)] transition-all"
                  placeholder="Message will auto-populate based on template…"
                />
                <p className="text-[10px] text-[#5a6a7e]">
                  You can edit the message freely. *bold* text will appear bold in WhatsApp.
                </p>
              </div>

              {/* Action Buttons */}
              <div className="flex flex-col gap-2.5 pt-1">
                {/* Primary: Open WhatsApp (no API needed) */}
                <button
                  onClick={handleOpenWhatsApp}
                  disabled={!canSend}
                  className="w-full flex items-center justify-center gap-2.5 py-3 rounded-xl font-black text-sm uppercase tracking-wider transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                  style={{
                    background: canSend ? "#25d366" : "#25d366",
                    color: "#fff",
                    boxShadow: canSend ? "0 0 20px rgba(37,211,102,0.3), 0 4px 12px rgba(0,0,0,0.3)" : "none",
                  }}
                >
                  <svg viewBox="0 0 24 24" className="w-5 h-5 fill-white">
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.890-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/>
                  </svg>
                  Open in WhatsApp
                </button>

                {/* Secondary: Send via backend (Twilio) */}
                <button
                  onClick={handleSendBackend}
                  disabled={!canSend || sending}
                  className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl cat-btn-secondary text-sm disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  <Send className="w-4 h-4" />
                  {sending ? "Sending via API…" : "Send via Twilio API"}
                  <span className="text-[9px] font-mono text-[#5a6a7e] ml-1">(requires credentials)</span>
                </button>

                <div className="flex items-center gap-2 text-[10px] text-[#5a6a7e] bg-[#0d1117] rounded-lg px-3 py-2 border border-[#21293a]">
                  <ExternalLink className="w-3 h-3 shrink-0" />
                  <span>
                    &ldquo;Open in WhatsApp&rdquo; works instantly with no setup. Twilio API requires{" "}
                    <code className="text-[#ffcd11]">TWILIO_*</code> env vars in <code className="text-[#ffcd11]">.env</code>.
                  </span>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>,
    document.body
  );
}
